apiVersion: v1
kind: Pod
metadata:
  name: bhagya-kubia-v2
  labels:
    create_method: manual
    env: prod  
spec:
  nodeSelector:
    env: qa
  containers:
    - name: example-pod
      image: bhagyam90/kubia
      ports:
        - containerPort: 8080
          protocol: TCP
