apiVersion: v1
kind: Pod
metadata:
  name: bhagya-kubia-v2
  labels:
    create_method: manual
    env: prod  
spec:
  nodeSelector:
    env: qa
  containers:
    - name: example-pod
      image: luksa/kubia-unhealthy
      ports:
        - containerPort: 8080
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 8080
        initialDelaySeconds: 15
        timeoutSeconds: 5
        periodSeconds: 10
        failureThreshold: 5
